version: '3'

services:
  bus:
    image: rabbitmq:3-management
    hostname: bus 
    volumes:
      - ./bus/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./bus/logs:/var/log/rabbitmq/log
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3 

  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  converter_a:
    build:
      context: .
      dockerfile: ./converter/Dockerfile
    volumes:
        - ./converter:/app
        - ./common:/app/common
        - ./nas:/nas
    depends_on:
      - bus

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - bus
    volumes:
        - ./api:/app
        - ./common:/app/common
        - ./nas:/nas
        - ./db:/var/db
    ports:
      - 5000:5000